config/routes.rb
Rails.application.routes.draw do
  
  root :to => 'products#index'

  resources :orderlines
  resources :orders
  resources :alsoboughts
  resources :lineitems
  resources :carts
  resources :categories
  resources :products
  resources :buyers
  resources :charges
  
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  post '/addtocart/:id' => 'products#addtocart' , as: :addtocart

  get '/search' => 'products#search'

end

app/models/lineitem.rb
# == Schema Information
#
# Table name: lineitems
#
#  id         :integer          not null, primary key
#  product_id :integer
#  cart_id    :integer
#  quantity   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Lineitem < ActiveRecord::Base

	belongs_to :cart
	belongs_to :product
	
end

app/controllers/lineitems_controller.rb
class LineitemsController < ApplicationController
  before_action :set_lineitem, only: [:show, :edit, :update, :destroy]

  # GET /lineitems
  # GET /lineitems.json
  def index
    @lineitems = Lineitem.all.order(:id)
    # Get line itemsf or the current loggedin buyer
    if @current_buyer.present?
        @lineitems = @current_buyer.lineitems.order(:id)
        # Calculate @cart_total_items 
        # Calculate @cart_total_amount
        @cart_total_items = 0  
        @cart_total_amount = 0
        @lineitems.each do |li|
          @cart_total_items += li.quantity
          @cart_total_amount += li.product.price
        end
    end
  end

  # GET /lineitems/1
  # GET /lineitems/1.json
  def show
  end

  # GET /lineitems/new
  def new
    @lineitem = Lineitem.new
  end

  # GET /lineitems/1/edit
  def edit
  end

  # POST /lineitems
  # POST /lineitems.json
  def create
    @lineitem = Lineitem.new(lineitem_params)

    respond_to do |format|
      if @lineitem.save
        format.html { redirect_to @lineitem, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @lineitem }
      else
        format.html { render :new }
        format.json { render json: @lineitem.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lineitems/1
  # PATCH/PUT /lineitems/1.json
  def update
    respond_to do |format|
      if @lineitem.update(lineitem_params)
        format.html { redirect_to lineitems_url, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render :edit }
        format.json { render json: @lineitem.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lineitems/1
  # DELETE /lineitems/1.json
  def destroy
    @lineitem.destroy
    respond_to do |format|
      format.html { redirect_to lineitems_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lineitem
      @lineitem = Lineitem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lineitem_params
      params.require(:lineitem).permit(:product_id, :cart_id, :quantity)
    end
end

app/helpers/lineitems_helper.rb
module LineitemsHelper
end

app/views/lineitems/_form.html.erb
<%= form_for(@lineitem) do |f| %>
  <% if @lineitem.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lineitem.errors.count, "error") %> prohibited this lineitem from being saved:</h2>

      <ul>
      <% @lineitem.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p><%= @lineitem.product.name %>

  <td><%= image_tag @lineitem.product.image, width: "130" %></td>

  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity, in: 1..1000000 %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit "Save", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/lineitems/edit.html.erb
<h1>Change Quantity</h1>

<%= render 'form' %>

<%= link_to 'Back', lineitems_path %>

app/views/lineitems/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Cart Contents</h2>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Quantity</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lineitems.each do |lineitem| %>
      <tr>
        <td><%= lineitem.product.name %></td>
        <td><%= number_with_delimiter(lineitem.quantity) %></td>
        <td><%= number_to_currency(lineitem.product.price * lineitem.quantity) %></td>
        <td><%= link_to 'Edit', edit_lineitem_path(lineitem) %></td>
        <td><%= link_to 'Remove', lineitem, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<tr>
  <td></td>
  <td></td>
  <td></td>
</tr>

<br>
<p>
Cart Total Items  :<%= number_with_delimiter(@current_buyer.cart_total_items) %>
</p>
<p>
Cart Total Amount :<%= number_to_currency(@current_buyer.cart_total_amount) %>
</p>

<br>

<% if @current_buyer.cart_total_amount > 0 %>
<td><%= button_to 'Pay Now', new_charge_path, method: :get, class: "btn btn-primary" %></td>
<% end %>

app/views/lineitems/new.html.erb
<h1>New Lineitem</h1>

<%= render 'form' %>

<%= link_to 'Back', lineitems_path %>

app/views/lineitems/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @lineitem.product_id %>
</p>

<p>
  <strong>Cart:</strong>
  <%= @lineitem.cart_id %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @lineitem.quantity %>
</p>

<%= link_to 'Edit', edit_lineitem_path(@lineitem) %> |
<%= link_to 'Back', lineitems_path %>