config/routes.rb
Rails.application.routes.draw do
  
  root :to => 'products#index'

  resources :orderlines
  resources :orders
  resources :alsoboughts
  resources :lineitems
  resources :carts
  resources :categories
  resources :products
  resources :buyers
  resources :charges
  
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  post '/addtocart/:id' => 'products#addtocart' , as: :addtocart

  get '/search' => 'products#search'

end

app/models/alsobought.rb
# == Schema Information
#
# Table name: alsoboughts
#
#  id         :integer          not null, primary key
#  product_id :integer
#  alsogot_id :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Alsobought < ActiveRecord::Base

	belongs_to :product, 
    	:class_name => 'Product', :foreign_key => 'product_id' 
  	belongs_to :alsogot, 
    	:class_name => 'Product', :foreign_key => 'alsogot_id' 

end

app/controllers/alsoboughts_controller.rb
class AlsoboughtsController < ApplicationController
  before_action :set_alsobought, only: [:show, :edit, :update, :destroy]

  # GET /alsoboughts
  # GET /alsoboughts.json
  def index
    @alsoboughts = Alsobought.all
  end

  # GET /alsoboughts/1
  # GET /alsoboughts/1.json
  def show
  end

  # GET /alsoboughts/new
  def new
    @alsobought = Alsobought.new
  end

  # GET /alsoboughts/1/edit
  def edit
  end

  # POST /alsoboughts
  # POST /alsoboughts.json
  def create
    @alsobought = Alsobought.new(alsobought_params)

    respond_to do |format|
      if @alsobought.save
        format.html { redirect_to @alsobought, notice: 'Alsobought was successfully created.' }
        format.json { render :show, status: :created, location: @alsobought }
      else
        format.html { render :new }
        format.json { render json: @alsobought.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /alsoboughts/1
  # PATCH/PUT /alsoboughts/1.json
  def update
    respond_to do |format|
      if @alsobought.update(alsobought_params)
        format.html { redirect_to @alsobought, notice: 'Alsobought was successfully updated.' }
        format.json { render :show, status: :ok, location: @alsobought }
      else
        format.html { render :edit }
        format.json { render json: @alsobought.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /alsoboughts/1
  # DELETE /alsoboughts/1.json
  def destroy
    @alsobought.destroy
    respond_to do |format|
      format.html { redirect_to alsoboughts_url, notice: 'Alsobought was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_alsobought
      @alsobought = Alsobought.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def alsobought_params
      params.require(:alsobought).permit(:product_id)
    end
end

app/helpers/alsoboughts_helper.rb
module AlsoboughtsHelper
end

app/views/alsoboughts/_form.html.erb
<%= form_for(@alsobought) do |f| %>
  <% if @alsobought.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@alsobought.errors.count, "error") %> prohibited this alsobought from being saved:</h2>

      <ul>
      <% @alsobought.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.number_field :product_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/alsoboughts/edit.html.erb
<h1 class="heading">Editing (Also-Bought)</h1>

<%= render 'form' %>

app/views/alsoboughts/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="heading">Listing (Also-Boughts)</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @alsoboughts.each do |alsobought| %>
      <tr>
        <td><%= alsobought.product_id %></td>
        <td><%= link_to 'Show', alsobought %></td>
        <td><%= link_to 'Edit', edit_alsobought_path(alsobought) %></td>
        <td><%= link_to 'Destroy', alsobought, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Alsobought', new_alsobought_path %>

app/views/alsoboughts/new.html.erb
<h1>New Alsobought</h1>

<%= render 'form' %>

<%= link_to 'Back', alsoboughts_path %>

app/views/alsoboughts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @alsobought.product_id %>
</p>

<%= link_to 'Edit', edit_alsobought_path(@alsobought) %> |
<%= link_to 'Back', alsoboughts_path %>