config/routes.rb
Rails.application.routes.draw do
  
  root :to => 'products#index'

  resources :orderlines
  resources :orders
  resources :alsoboughts
  resources :lineitems
  resources :carts
  resources :categories
  resources :products
  resources :buyers
  resources :charges
  
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  post '/addtocart/:id' => 'products#addtocart' , as: :addtocart

  get '/search' => 'products#search'

end

app/models/orderline.rb
# == Schema Information
#
# Table name: orderlines
#
#  id           :integer          not null, primary key
#  product_name :string
#  quantity     :integer
#  total_price  :decimal(, )
#  product_id   :integer
#  order_id     :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Orderline < ActiveRecord::Base

	belongs_to :product
	belongs_to :order

end

app/controllers/orderlines_controller.rb
class OrderlinesController < ApplicationController
  before_action :set_orderline, only: [:show, :edit, :update, :destroy]

  # GET /orderlines
  # GET /orderlines.json
  def index
    @orderlines = Orderline.all
  end

  # GET /orderlines/1
  # GET /orderlines/1.json
  def show
  end

  # GET /orderlines/new
  def new
    @orderline = Orderline.new
  end

  # GET /orderlines/1/edit
  def edit
  end

  # POST /orderlines
  # POST /orderlines.json
  def create
    @orderline = Orderline.new(orderline_params)

    respond_to do |format|
      if @orderline.save
        format.html { redirect_to @orderline, notice: 'Orderline was successfully created.' }
        format.json { render :show, status: :created, location: @orderline }
      else
        format.html { render :new }
        format.json { render json: @orderline.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orderlines/1
  # PATCH/PUT /orderlines/1.json
  def update
    respond_to do |format|
      if @orderline.update(orderline_params)
        format.html { redirect_to @orderline, notice: 'Orderline was successfully updated.' }
        format.json { render :show, status: :ok, location: @orderline }
      else
        format.html { render :edit }
        format.json { render json: @orderline.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orderlines/1
  # DELETE /orderlines/1.json
  def destroy
    @orderline.destroy
    respond_to do |format|
      format.html { redirect_to orderlines_url, notice: 'Orderline was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_orderline
      @orderline = Orderline.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def orderline_params
      params.require(:orderline).permit(:product_name, :quantity, :total_price, :product_id, :order_id)
    end
end

app/helpers/orderlines_helper.rb
module OrderlinesHelper
end

app/views/orderlines/_form.html.erb
<%= form_for(@orderline) do |f| %>
  <% if @orderline.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@orderline.errors.count, "error") %> prohibited this orderline from being saved:</h2>

      <ul>
      <% @orderline.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_name %><br>
    <%= f.text_field :product_name %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="field">
    <%= f.label :total_price %><br>
    <%= f.text_field :total_price %>
  </div>
  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.number_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :order_id %><br>
    <%= f.number_field :order_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orderlines/edit.html.erb
<h1>Editing Orderline</h1>

<%= render 'form' %>

<%= link_to 'Show', @orderline %> |
<%= link_to 'Back', orderlines_path %>

app/views/orderlines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Orderlines</h1>

<table>
  <thead>
    <tr>
      <th>Product name</th>
      <th>Quantity</th>
      <th>Total price</th>
      <th>Product</th>
      <th>Order</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orderlines.each do |orderline| %>
      <tr>
        <td><%= orderline.product_name %></td>
        <td><%= orderline.quantity %></td>
        <td><%= orderline.total_price %></td>
        <td><%= orderline.product_id %></td>
        <td><%= orderline.order_id %></td>
        <td><%= link_to 'Show', orderline %></td>
        <td><%= link_to 'Edit', edit_orderline_path(orderline) %></td>
        <td><%= link_to 'Destroy', orderline, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Orderline', new_orderline_path %>

app/views/orderlines/new.html.erb
<h1>New Orderline</h1>

<%= render 'form' %>

<%= link_to 'Back', orderlines_path %>

app/views/orderlines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product name:</strong>
  <%= @orderline.product_name %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @orderline.quantity %>
</p>

<p>
  <strong>Total price:</strong>
  <%= @orderline.total_price %>
</p>

<p>
  <strong>Product:</strong>
  <%= @orderline.product_id %>
</p>

<p>
  <strong>Order:</strong>
  <%= @orderline.order_id %>
</p>

<%= link_to 'Edit', edit_orderline_path(@orderline) %> |
<%= link_to 'Back', orderlines_path %>