config/routes.rb
Rails.application.routes.draw do
  
  root :to => 'products#index'

  resources :orderlines
  resources :orders
  resources :alsoboughts
  resources :lineitems
  resources :carts
  resources :categories
  resources :products
  resources :buyers
  resources :charges
  
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  post '/addtocart/:id' => 'products#addtocart' , as: :addtocart

  get '/search' => 'products#search'

end

app/models/alsobought.rb
# == Schema Information
#
# Table name: alsoboughts
#
#  id         :integer          not null, primary key
#  product_id :integer
#  alsogot_id :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Alsobought < ActiveRecord::Base

	belongs_to :product, 
    	:class_name => 'Product', :foreign_key => 'product_id' 
  	belongs_to :alsogot, 
    	:class_name => 'Product', :foreign_key => 'alsogot_id' 

end

app/models/buyer.rb
# == Schema Information
#
# Table name: buyers
#
#  id              :integer          not null, primary key
#  name            :string
#  email           :string
#  password_digest :string
#  address         :string
#  suburb          :string
#  city            :string
#  state           :string
#  post_code       :string
#  country         :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Buyer < ActiveRecord::Base

	has_secure_password
	
	has_one :cart

    has_many :lineitems, :through => :cart

    has_many :orders

  	validates :name, :presence => true, :uniqueness => true, :length => { :minimum => 3 }
	validates :email, :presence => true, :uniqueness => true
	validates :address, :presence => true
	validates :city, :presence => true
	validates :state, :presence => true
	validates :post_code, :presence => true
	validates :country, :presence => true

	def cart_total_items
		total = 0
		if lineitems.present?
			lineitems.each do |li|
				total += li.quantity 
			end	
		end
		return total
	end

	def cart_total_amount
		total = 0
		if lineitems.present?
			lineitems.each do |li|
				total += li.product.price * li.quantity
			end
		end
		return total
	end	

end	

app/models/cart.rb
# == Schema Information
#
# Table name: carts
#
#  id         :integer          not null, primary key
#  buyer_id   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Cart < ActiveRecord::Base

	has_many :lineitems, :dependent => :destroy
	belongs_to :buyer

end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Category < ActiveRecord::Base

	has_many :products

end

app/models/lineitem.rb
# == Schema Information
#
# Table name: lineitems
#
#  id         :integer          not null, primary key
#  product_id :integer
#  cart_id    :integer
#  quantity   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Lineitem < ActiveRecord::Base

	belongs_to :cart
	belongs_to :product
	
end

app/models/order.rb
# == Schema Information
#
# Table name: orders
#
#  id         :integer          not null, primary key
#  name       :string
#  email      :string
#  address    :string
#  suburb     :string
#  state      :string
#  post_code  :string
#  country    :string
#  shipped    :date
#  buyer_id   :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Order < ActiveRecord::Base

	belongs_to :buyer

	has_many :orderlines, :dependent => :destroy

end

app/models/orderline.rb
# == Schema Information
#
# Table name: orderlines
#
#  id           :integer          not null, primary key
#  product_name :string
#  quantity     :integer
#  total_price  :decimal(, )
#  product_id   :integer
#  order_id     :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Orderline < ActiveRecord::Base

	belongs_to :product
	belongs_to :order

end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id          :integer          not null, primary key
#  name        :string
#  description :text
#  price       :decimal(, )
#  list_price  :decimal(, )
#  image       :string
#  available   :boolean
#  quantity    :integer
#  postage     :decimal(, )
#  category_id :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Product < ActiveRecord::Base

	has_many :lineitems

  has_many :orderlines

	belongs_to :category

	has_many :relations_to, 
    	:foreign_key => 'product_id',  :class_name => 'Alsobought' 
  has_many :relations_from, 
    	:foreign_key => 'alsogot_id', :class_name => 'Alsobought'                             

  has_many :also_bought, 
    	:through => :relations_to,   :source => :alsogot
  has_many :bought_with, 
    	:through => :relations_from, :source => :product

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
  end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
      if @cart.update(cart_params)
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to carts_url, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.require(:cart).permit(:buyer_id)
    end
end

app/helpers/alsoboughts_helper.rb
module AlsoboughtsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def active_class(link_path)
		if current_page?(link_path)
			"active"
		else
			""
		end
	end
end

app/helpers/buyers_helper.rb
module BuyersHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/lineitems_helper.rb
module LineitemsHelper
end

app/helpers/orderlines_helper.rb
module OrderlinesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>myCartify</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <a href="/" class="navbar-brand"><span class="logo">myCartify</span></a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="<%= active_class(root_path) %>"><a href="/">Home</a></li>
        <li class="<%= active_class(search_path) %>"><%= link_to "Search", search_path %></li>

        <li class="dropdown">
            <a href="<%= products_path %>" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Categories<span class="caret"></span></a>
            <ul class="dropdown-menu">
               <% Category.all.order(:name).each do |c| %>
                  <li><%= link_to c.name, products_path(cat_id: c.id) %></li>
               <% end %> 
            </ul>   
        </li>    

        <% if @current_buyer.present? %>
          <li class="<%= active_class(edit_buyer_path(@current_buyer)) %>"><%= link_to 'Edit My Profile', edit_buyer_path(@current_buyer) %></li>
          <li class="<%= active_class(lineitems_path) %>"><%= link_to "My Cart (#{ pluralize(@current_buyer.cart_total_items,'Item')})", lineitems_path %></li>
          <% if @current_buyer.admin %>
              <li class="<%= active_class(orders_path) %>"><%= link_to 'Show Orders', orders_path %></li>
          <% end %>
          <li><%= link_to "Logout (#{ @current_buyer.name })", login_path, :method => 'delete', :data => { :confirm => 'Are you sure you wish to logout?' } %></li>
        <% else %>
          <li class="<%= active_class(new_buyer_path) %>"><%= link_to 'Register', new_buyer_path %></li>
          <li class="<%= active_class(login_path) %>"><%= link_to 'Login', login_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<!-- EDIT LATER -->
<div class="theheader">
  <div class="col-md-10 col-md-offset-1">
    <!-- <h2>MyCartify sells something for everyone.</h2> -->
    <p class="lead">We sell worldwide and ship our products within the same day of purchase.</p>
  </div>
</div><!-- /.container -->

<div class="yeah"></div>

<div class="container">
  <div class="row">
    <div class="col-md-10">
      <%= yield %>
    </div>
  </div>
</div>

<div id="footer">
  <footer>
    <hr />
    <p>myCartify was created by Guy Chamberlain, Kylie O'Brien-Pratt and <a href="https://media.giphy.com/media/ScZzMlETdv9mg/giphy.gif" class="doge">T-Dizzle-Dazzle-Dawwwg</p>
  </footer>
</div>

</body>
</html>